# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/derek/go/src/github.com/derek.boucher/FuuGBemu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/derek/go/src/github.com/derek.boucher/FuuGBemu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derek/go/src/github.com/derek.boucher/FuuGBemu/CMakeFiles /home/derek/go/src/github.com/derek.boucher/FuuGBemu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derek/go/src/github.com/derek.boucher/FuuGBemu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FuuGBemu

# Build rule for target.
FuuGBemu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FuuGBemu
.PHONY : FuuGBemu

# fast build rule for target.
FuuGBemu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/build
.PHONY : FuuGBemu/fast

src/Cpu.o: src/Cpu.cpp.o

.PHONY : src/Cpu.o

# target to build an object file
src/Cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Cpu.cpp.o
.PHONY : src/Cpu.cpp.o

src/Cpu.i: src/Cpu.cpp.i

.PHONY : src/Cpu.i

# target to preprocess a source file
src/Cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Cpu.cpp.i
.PHONY : src/Cpu.cpp.i

src/Cpu.s: src/Cpu.cpp.s

.PHONY : src/Cpu.s

# target to generate assembly for a file
src/Cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Cpu.cpp.s
.PHONY : src/Cpu.cpp.s

src/Gameboy.o: src/Gameboy.cpp.o

.PHONY : src/Gameboy.o

# target to build an object file
src/Gameboy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Gameboy.cpp.o
.PHONY : src/Gameboy.cpp.o

src/Gameboy.i: src/Gameboy.cpp.i

.PHONY : src/Gameboy.i

# target to preprocess a source file
src/Gameboy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Gameboy.cpp.i
.PHONY : src/Gameboy.cpp.i

src/Gameboy.s: src/Gameboy.cpp.s

.PHONY : src/Gameboy.s

# target to generate assembly for a file
src/Gameboy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Gameboy.cpp.s
.PHONY : src/Gameboy.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Memory.o: src/Memory.cpp.o

.PHONY : src/Memory.o

# target to build an object file
src/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Memory.cpp.o
.PHONY : src/Memory.cpp.o

src/Memory.i: src/Memory.cpp.i

.PHONY : src/Memory.i

# target to preprocess a source file
src/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Memory.cpp.i
.PHONY : src/Memory.cpp.i

src/Memory.s: src/Memory.cpp.s

.PHONY : src/Memory.s

# target to generate assembly for a file
src/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Memory.cpp.s
.PHONY : src/Memory.cpp.s

src/Ppu.o: src/Ppu.cpp.o

.PHONY : src/Ppu.o

# target to build an object file
src/Ppu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Ppu.cpp.o
.PHONY : src/Ppu.cpp.o

src/Ppu.i: src/Ppu.cpp.i

.PHONY : src/Ppu.i

# target to preprocess a source file
src/Ppu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Ppu.cpp.i
.PHONY : src/Ppu.cpp.i

src/Ppu.s: src/Ppu.cpp.s

.PHONY : src/Ppu.s

# target to generate assembly for a file
src/Ppu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/Ppu.cpp.s
.PHONY : src/Ppu.cpp.s

src/opengl/Shader.o: src/opengl/Shader.cpp.o

.PHONY : src/opengl/Shader.o

# target to build an object file
src/opengl/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Shader.cpp.o
.PHONY : src/opengl/Shader.cpp.o

src/opengl/Shader.i: src/opengl/Shader.cpp.i

.PHONY : src/opengl/Shader.i

# target to preprocess a source file
src/opengl/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Shader.cpp.i
.PHONY : src/opengl/Shader.cpp.i

src/opengl/Shader.s: src/opengl/Shader.cpp.s

.PHONY : src/opengl/Shader.s

# target to generate assembly for a file
src/opengl/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Shader.cpp.s
.PHONY : src/opengl/Shader.cpp.s

src/opengl/Vao.o: src/opengl/Vao.cpp.o

.PHONY : src/opengl/Vao.o

# target to build an object file
src/opengl/Vao.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Vao.cpp.o
.PHONY : src/opengl/Vao.cpp.o

src/opengl/Vao.i: src/opengl/Vao.cpp.i

.PHONY : src/opengl/Vao.i

# target to preprocess a source file
src/opengl/Vao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Vao.cpp.i
.PHONY : src/opengl/Vao.cpp.i

src/opengl/Vao.s: src/opengl/Vao.cpp.s

.PHONY : src/opengl/Vao.s

# target to generate assembly for a file
src/opengl/Vao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Vao.cpp.s
.PHONY : src/opengl/Vao.cpp.s

src/opengl/Vbo.o: src/opengl/Vbo.cpp.o

.PHONY : src/opengl/Vbo.o

# target to build an object file
src/opengl/Vbo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Vbo.cpp.o
.PHONY : src/opengl/Vbo.cpp.o

src/opengl/Vbo.i: src/opengl/Vbo.cpp.i

.PHONY : src/opengl/Vbo.i

# target to preprocess a source file
src/opengl/Vbo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Vbo.cpp.i
.PHONY : src/opengl/Vbo.cpp.i

src/opengl/Vbo.s: src/opengl/Vbo.cpp.s

.PHONY : src/opengl/Vbo.s

# target to generate assembly for a file
src/opengl/Vbo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FuuGBemu.dir/build.make CMakeFiles/FuuGBemu.dir/src/opengl/Vbo.cpp.s
.PHONY : src/opengl/Vbo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FuuGBemu"
	@echo "... src/Cpu.o"
	@echo "... src/Cpu.i"
	@echo "... src/Cpu.s"
	@echo "... src/Gameboy.o"
	@echo "... src/Gameboy.i"
	@echo "... src/Gameboy.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Memory.o"
	@echo "... src/Memory.i"
	@echo "... src/Memory.s"
	@echo "... src/Ppu.o"
	@echo "... src/Ppu.i"
	@echo "... src/Ppu.s"
	@echo "... src/opengl/Shader.o"
	@echo "... src/opengl/Shader.i"
	@echo "... src/opengl/Shader.s"
	@echo "... src/opengl/Vao.o"
	@echo "... src/opengl/Vao.i"
	@echo "... src/opengl/Vao.s"
	@echo "... src/opengl/Vbo.o"
	@echo "... src/opengl/Vbo.i"
	@echo "... src/opengl/Vbo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

